import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import classNames from 'classnames';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [time, setTime] = useState(new Date())

  useEffect(() => {
    const interval = setInterval(() => {
      setTime(new Date())
    }, 1000)
    return () => clearInterval(interval)
  }, [])

  const formatTime = (date: Date) => {
    
    const hours = date.getHours()
    const minutes = date.getMinutes()
    const seconds = date.getSeconds()
    const ampm = hours >= 12 ? 'PM' : 'AM'
    const formattedHours = hours % 12 || 12
    return `${formattedHours}:${minutes
      .toString()
      .padStart(2, '0')}:${seconds.toString().padStart(2, '0')} ${ampm}`
  }

  const formatDate = (date: Date) => {
    const day = date.getDay()
    const month = date.getMonth()
    const year = date.getFullYear()
    const dayOfMonth = date.getDate()
    return `${dayOfMonth}-${month}-${year}`
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className={'main'}>
        <div className={'clock-container bg-blue-500 text-white font-bold px-4 py-2'}>
          <h1
            className={styles.time}
            dangerouslySetInnerHTML={{ __html: formatTime(time) }}
          />
          <h1 className={styles.time}
            dangerouslySetInnerHTML={{ __html: formatDate(time) }}/>
        </div>
      </main>
    </>
  )
}